[package]
name = "llm"
version = "0.1.0"
edition = "2021"

[lib]
name = "llm"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
